UI/Controllers/ProductDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.Models;
using System.Web.Security;
using Advisor.Dal.Domain;
using UI.Builders;
using Advisor.Data;

namespace UI.Controllers
{
    public class ProductDataController : ControllerBase
    {
        private readonly IProductManager _productManager
            = Services.Factory.Get<IProductManager>();
        private readonly ProductBuilder _productBuilder
            = new ProductBuilder();
 
        private readonly ICommentManager _commentManager
            = Services.Factory.Get<ICommentManager>();
        private readonly CommentBuilder _commentBuilder
            = new CommentBuilder();

        private readonly IUserManager _userManager
         = Services.Factory.Get<IUserManager>();

        private readonly IProductPhotoManager _photoManager
            = Services.Factory.Get<IProductPhotoManager>();
        private readonly ICategoryManager _categoryManager
        = Services.Factory.Get<ICategoryManager>();
        private readonly IRatingManager _ratingManager
       = Services.Factory.Get<IRatingManager>();

        //главная страница продукта
        public ActionResult Index(int? id)
        {
            if (id==null)
            {
                return HttpNotFound();
            }
            var product=_productManager.Get((int)id);
            if (product==null)
            {
                return HttpNotFound();
            }
            return View(_productBuilder.Build(product));
        }


        //добавление комментария        
        [HttpPost, ActionName("Index")]
        public ActionResult AddComment(ProductModel model,String Comment,int? Rating)
        {
            //тут добавляется комментарий
            if (Comment == "")
            {
                ModelState.AddModelError("", "Отзыв не может быть пустым");
                return View(model);
            }
            if (Rating==null)
            {
                ModelState.AddModelError("", "Поставьте оценку предложению");
                return View(model);
            }
            _commentManager.Add(CurrentUser.Id, model.Id, Comment);
            _ratingManager.Add(CurrentUser.Id, model.Id, (int)Rating);
            return Redirect("/ProductData/Index/" + model.Id);
        }


        public ActionResult Comments(int? id)
        {
            if (id==null)
            {
                return HttpNotFound();
            }
            return View(_commentBuilder.BuildIEnumerable(_commentManager.GetAllByProduct((int)id)));
        }




        //изменение продукта
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id==null)
            {
                return HttpNotFound();
            }
            var product = _productManager.Get((int)id);
            if (product == null)
            {
                return HttpNotFound();
            }
            
            ProductModel model = _productBuilder.Build(product);
            ViewBag.Categories = _categoryManager.GetAllCategories();//добавляем категории
            return View(model);
        }

        //тут еще нет, собсственно сохранения
        [HttpPost]
        public ActionResult Edit(ProductModel model)
        {
            if (ModelState.IsValid)
            {
                _productManager.SaveChanges(model.Id, model.Name, model.Info, model.MinValue, model.MaxValue, model.Category);
                return Redirect("/");
            }
            ViewBag.Categories = _categoryManager.GetAllCategories();
            return View();
        }


        //на этот метод приходят user, когда вбивает в командной строке
        public ActionResult Add()
        {
            if (CurrentUser == null)
            {//надо зарегаться чтобы добавлять что-либо
                //поэтому просто выкинем человека на главную Х)
                return Redirect("/");
            }
            ViewBag.Categories = _categoryManager.GetAllCategories();
            return View();
        }

        [HttpPost]
        public ActionResult Add(ProductModel model,HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                Product p = _productManager.Add(CurrentUser.Id, model.Name, model.Info, model.MinValue, model.MaxValue, model.Category);
                /*if ((p!=null) && (image != null))
                {//если есть изображение, то добавляем его в базу
                    ProductPhoto Photo = new ProductPhoto();
                    Photo.MimeType = image.ContentType;
                    Photo.Photo = new byte[image.ContentLength];
                    image.InputStream.Read(Photo.Photo, 0, image.ContentLength);
                    Photo=_photoManager.Add(Photo.Photo, Photo.MimeType, p.Id);
                    model.PhotosId.Add(Photo.Id);
                    //а также ее id к модели
                }*/
                //проверка поскольку категория может оказаться не той.
                if (p!=null) 
                {
                    TempData["message"] = string.Format("{0} услуга была сохранена", p.Name);
                    return Redirect("/");
                }
                //странно, что если ты не указал категорию верно, тебя сразу выкидывают на главню
                else
                    //TempData["message"] = string.Format("Сохранение невозможно, укажите имеющуюся категорию");
                {
                    ModelState.AddModelError("Categories", "Введенной вами категории не существует");
                    ViewBag.Categories = _categoryManager.GetAllCategories();
                    return View();
                }
            }
            else
            {//что-то пошло не так
                ViewBag.Categories = _categoryManager.GetAllCategories();
                return View();
            }
        }

        //это уже не нужно
     /*   public FileContentResult GetImage(int productId)
        {
            Product prod = _productManager.Get(productId);
            List<FileContentResult> ListPhotos = new List<FileContentResult>();
            //Product prod = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (prod != null)
            {
                //     return File(prod.ImageData, prod.ImageMimeType);
                foreach (var p in _photoManager.GetPhotos(productId))
                { ListPhotos.Add(File(p.Photo, p.MimeType));  }
                return ListPhotos[ListPhotos.Count-1];
            }
            else
            {
                return null;
            }
        }*/

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id==null)
            {
                return HttpNotFound();//пусть так
            }
            return View();
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            _productManager.Delete((int)id);
            return RedirectToAction("Index");
        }
    }
}

UI/Views/ProductData/Add.cshtml
@using System.Web.Mvc
@model UI.Models.ProductModel
@{
    ViewBag.Title = "Добавление товара";
}
<br>
<table>
    <tr>
        @using (Html.BeginForm("Add", "ProductData", FormMethod.Post))
        {

            @Html.ValidationSummary(true)
            <td width="100%">

                <h2><font color="green"><center> Добавление нового товара </center></font></h2>
                <br>
                <br>
                <table border="0" width="100%" align="center">
                    <tr>
                        <td align="center" width="50%"><b>Введите название товара(услуги): </b></td>
                        <td>@Html.TextBox("Name")</td>
                        <td>@Html.ValidationMessage("Name")</td>
                    </tr>
                    <tr>
                        <td align="center" width="50%"><b>Введите информацию о товаре(услуге): </b></td>
                        <td>@Html.TextArea("Info")</td>
                    </tr>
                    <tr>
                        <td align="center" width="50%"><b>Введите минимальную цену: </b></td>
                        <td>@Html.TextBox("MinValue")</td>
                    </tr>
                    <tr>
                        <td align="center" width="50%"><b>Введите максимальную цену: </b></td>
                        <td>@Html.TextBox("MaxValue")</td>
                    </tr>
                    <tr>
                        <td align="center" width="50%"><b>Выберите категорию </b></td>
                        @*<td>@Html.TextBox("Category")</td>*@
                        <td>@Html.DropDownList("Category",new SelectList(ViewBag.Categories))</td>
                        <td>@Html.ValidationMessage("Category")</td>
                        
                    </tr>
                    @*<input type=hidden value=1 name= type>*@
                    
                    <tr>
                        <td align ="center" width="100%">
                          <br />  <input type=submit value="Добавить предложение">
                        </td>
                    </tr>
                    <tr>
                       <td align="center" width="100%">
                          <br />  <a>*Добавить фото к предложению можно при редактировании </a>

                        </td>
                    </tr>
                    
                </table>
            </td>
            <td width="20%"></td>
        }

    </tr>
</table>

UI/Views/ProductData/Comments.cshtml
@using System.Collections.Generic;
@using UI.Models;
@model IEnumerable<CommentModel>
    @{
        ViewBag.Title = "Отзывы";
    }
    <br>
    <table>
        <tr>

            <td width="30%"></td>
            <td width="100%"> 
                
                <table >
                <h2><font color="green"><center> Отзывы на товар или продукт:<br><br></center></font></h2>
                @*<br><br>
    <hr width="100%" align="left">*@
                @if (Model.Count() == 0)
                {
                    <p>К сожалению, еще никто не оставил отзывов на это предложение</p>
                }
                else
                {
                    foreach (CommentModel b in Model)
                    {

                        <tr bgcolor="yellow">

                            <td align="left" width="30%">

                                <a href="/UserData/Index/@b.Id">@b.AuthorLogin</a>

                            </td>
                            <td align="left" width="30%">
                                Оценка: @b.Rating
                            </td>
                            <td align="right" width="30%"><font color="green">@b.DateOfCreate</font></td>

                        </tr>
                    <tr>
                    <td>@b.Text</td>
                </tr>
                    }
                }
                </table>
                </td>
                <td width="20%"></td>

                
                </tr>
            </table>

UI/Views/ProductData/Edit.cshtml
@using System.Web.Mvc
@model UI.Models.ProductModel

@{
    ViewBag.Title = "Редактирование предложения";
}

<h2>Редактирование предложения</h2>
@using (Html.BeginForm("Edit", "ProductData", FormMethod.Post))
{
    <fieldset>
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.UserLogin)
        @Html.HiddenFor(m => m.DateOfCreate)
        @Html.HiddenFor(m => m.Rating)
        <p>
            @Html.LabelFor(m => m.Name, "Название товара")
            <br />
            @Html.EditorFor(m => m.Name)
        </p>
        <p>
            @Html.LabelFor(m => m.Info, "Информация")
            <br />
            @Html.EditorFor(m => m.Info)
        </p>
        <p>
            @Html.LabelFor(m => m.MinValue, "Минимальная цена")
            <br />
            @Html.EditorFor(m => m.MinValue)
        </p>
        <p>
            @Html.LabelFor(m => m.MaxValue, "Максимальная цена")
            <br />
            @Html.EditorFor(m => m.MaxValue)
        </p>
        <p>
            @Html.LabelFor(m => m.Category, "Категория")
            <br />
            @*Html.EditorFor(m => m.Category)*@
            @Html.DropDownList("Category", new SelectList(ViewBag.Categories));
        </p>
        <p>
            <a href="/ProductPhoto/Add/@Model.Id">Добавить фото</a> 
            <br />
        </p>
        <p>
            <a href="/ProductPhoto/Index/@Model.Id">Посмотреть фото</a> 
            <br />
        </p>
        <p><input type="submit" value="Сохранить изменения" /></p>
    </fieldset>
}

UI/Views/ProductData/Index.cshtml
@using System.Web.Mvc
@using Advisor.Data;
@model UI.Models.ProductModel

@{
    ViewBag.Title = "Главная страница товара";
}
<br>
<table>
    <tr>

        @using (Html.BeginForm("Index", "ProductData", FormMethod.Post))
        {
        <td width="20%"></td>
            <td width="50%">
                <h2><font color="green"><center> Главная страница товара </center></font></h2>
                <br><br>
                <table border="0" width="100%" align="center">
                    <tr>

                        <td>
                            @Html.HiddenFor(m => m.Id)
                            <a href="/UserData/Index/?login=@Model.UserLogin">@Model.UserLogin</a>
                        </td>
                        <td> @Html.DisplayFor(m => m.DateOfCreate)</td>
                    </tr>
                    <tr><td></td></tr>
                    @if (Model.Rating != 0)
                    {
                        @Html.DisplayFor(m => m.Rating)
                    }
                    <tr>
                        <td> @Html.LabelFor(m => m.Name, "Название товара")</td>
                        <td>@Html.DisplayFor(m => m.Name)</td>
                    </tr>
                    <tr>
                        <td>                    @Html.LabelFor(m => m.Info, "Информация")                    </td>
                        <td>                @Html.DisplayFor(m => m.Info)                </td>
                    </tr>

                    <tr>
                        <td>             @Html.LabelFor(m => m.MinValue, "Минимальная цена")                    </td>
                        <td>             @Html.DisplayFor(m => m.MinValue)                </td>
                    </tr>
                    <tr>
                        <td>                @Html.LabelFor(m => m.MaxValue, "Максимальная цена")            </td>
                        <td>             @Html.DisplayFor(m => m.MaxValue)                               </td>
                    </tr>
                    <tr>
                        <td> @Html.LabelFor(m => m.Category, "Категория")</td>
                        <td>@Html.DisplayFor(m => m.Category)</td>
                    </tr>
                </table>
            </td>
            

                if (ViewBag.IsAuthorized && ViewBag.Login == Model.UserLogin)
                {
               
                    <a href="/ProductData/Edit/@Model.Id">Редактировать товар</a>
                
                }
                else
                {
                
             <img src="/Content/Images/палец_вверх.jpg" width="70" height="70" onclick='this.src = "/Content/Images/палец_вверх_нажато.png"' />
            
                    <img src="/Content/Images/палец_вниз.jpg" width="70" height="70" onclick='this.src = "/Content/Images/палец_вниз_нажато.png"' />
            

                @*//поле для оставления оценок
            //!!!!! хочу здесь звездочки!!! Алсу, ты умеешь?
            //а еще как-то нужно сделать так, чтобы ты не могу голосовать больше 1го раза

            //using (Html.BeginForm("Edit", "ProductData", FormMethod.Post))
            {
            @Html.TextBox("Rating");//пусть пока это, тут должна быть оценка
            //p><input type="submit" value="Оставить" /></p>*@
                }
                }

                @*//поле для комментариев*@
                @if (ViewBag.IsAuthorized)
                {
                    ICommentManager cm=Services.Factory.Get<ICommentManager>();
                    if (cm.Get(ViewBag.UserId,Model.Id)==null)
                    { 
                    @Html.ValidationSummary()
                    @Html.TextArea("Comment");
                    @Html.DropDownList("Rating", new SelectList(new int[] { 1, 2, 3, 4,5 }))
                    <p><input type="submit" value="Оставить отзыв" /></p>
                }
                @Html.Display("Вы уже оставляли отзыв на товар")
                }
                else
                {
                @Html.Display("К сожалению, только авторизированные пользователи могут оставлять комментарии")
                }
                {
           <a href="/ProductData/Comments/@Model.Id">Все отзывы на товар</a>
                }
                @*/а вот тут должны отображаться уже оставленные комментарии
            //Но их пока нет
            //оставь для них место, ладно?*@
        
        }
</table>