UI/Controllers/UserDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Advisor.Data;
using UI.Models;
using System.Web.Security;
using UI.Builders;

namespace UI.Controllers
{
    public class UserDataController : ControllerBase
    {
        private readonly IUserManager _userManager
            = Services.Factory.Get<IUserManager>();
        private readonly UserBuilder _userBuilder
            =new UserBuilder();


        public ActionResult Index(string login)
        {
            if (login != "")
            {
                var user = _userManager.Get(login);
                //если такой пользователь не существует
                if (user != null)
                {
                    return View(_userBuilder.Build(user));
                }
                return HttpNotFound();
            }
            return Redirect("/");
        }

        public ActionResult Register()
        {
            if (CurrentUser == null)
            {
                return View();
            }
            return Redirect("/");
        }

        [HttpPost]
        public ActionResult Register(UserModel model)
        {
            if (ModelState.IsValid)
            {
                //если такой уже есть, то вернет Null
                var user = _userManager.Register(model.Login, model.Password, model.Name, model.Sirname, model.Email, model.Info);
                if (user == null)
                {
                    ModelState.AddModelError("Login", "Введенный логин не уникален");
                    return View();
                }
                return Redirect("/");
            }

            return View();
        }

        public ActionResult Edit()
        {
            if (this.CurrentUser != null)
            {
                return View(_userBuilder.Build(CurrentUser));
            }
            else return Redirect("/");
        }
        
        [HttpPost]
        public ActionResult Edit(UserModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _userManager.Get(model.Login);
                if (user == null || user.Id==model.Id)
                {
                    _userManager.ChangeLogin(model.Id, model.Login);
                    _userManager.ChangeData(model.Id, model.Name, model.Sirname, model.Email, model.Info);
                    ModelState.AddModelError("","Изменения сохранены");
                    return View();
                }
                ModelState.AddModelError("Login", "Такой логин уже существует");
                return View();
            }
            return View();
        }

        [HttpPost]
        public ActionResult EditPassword(UserModel model, string oldPassword)
        {
            if (ModelState.IsValid)
            {
                var user=_userManager.ChangePassword(model.Id, oldPassword, model.Password);
                if (user != null)//если пароль верен
                {
                    return Redirect("/UserData/Index");
                }
                ViewBag.oldPasswordMessage = "Введенный пароль неверен";
                return View("Edit");
            }
            return View("Edit");
        }

        //
        public ActionResult AllProducts(string login)
        {
            if (login !="")
            {
                var user=_userManager.Get(login);
                //если такой пользователь не существует
                if (user != null)
                {
                    ProductBuilder pb = new ProductBuilder();
                    IEnumerable<ProductModel> products = pb.BuildIEnumerable(_userManager.GetProducts(user.Id));
                    return View(products);
                }
                return HttpNotFound();
            }
            return Redirect("/");
        }
    }
}

UI/Views/UserData/AllProducts.cshtml
@using System.Collections.Generic;
@using UI.Models;
@model IEnumerable<ProductModel>
    @{
        ViewBag.Title = "Все предложения";
    }
    <br>
    <table>
        <tr>

            <td width="25%"></td>
            <td width="50%">
                <h2><font color="green"><center> Все предложения </center></font></h2>
                <br><br>
                <table border="0" width="100%" align="center" cellpadding="20">
                    @if (Model.Count() == 0)
                    {
                        <p>Не добавлено еще ни одного предложения</p>
                    }
                    else
                    {
                        <tr bgcolor="green">
                                <td>Товар</td>
                                <td>Категория</td>
                                <td>Рейтинг</td>
                                <td>Мин цена</td>
                            </tr>
                        foreach (ProductModel b in Model)
                        {

                            <tr>
                                <td><p><a href="/ProductData/Index/@b.Id">@b.Name</a></p></td>
                                <td><p>@b.Category</p></td>
                                <td><p>@b.Rating</p></td>
                                <td><p>от @b.MinValue рублей</p></td>
                            </tr>
                        }
                    }
                </table>
            <td width="25%"></td>
        </tr>
    </table>

UI/Views/UserData/Edit.cshtml
@model UI.Models.UserModel

@{
    ViewBag.Title = "Редактирование личных данных";
}
<br>
<table>
    <tr>
        

        @using (Html.BeginForm("Edit", "UserData", FormMethod.Post))
        {
            @Html.ValidationSummary(true)
        <td width="10%"></td>
    <td width="40%">

        <h2><font color="green"><center> Изменение данных пользователя </center></font></h2>
        <br><br>
        <table border="0" width="100%" align="center">
            <tr>

                @Html.HiddenFor(m => m.Id)
                @Html.HiddenFor(m => m.Password)
                @Html.HiddenFor(m => m.PasswordClone)

                <td align="center" width="50%"><b>Логин: </b></td>
                <td>@Html.EditorFor(m => m.Login)</td>
                <td>@Html.ValidationMessage("Login")</td>
            </tr>
            <tr>
                <td align="center" width="50%"><b>Имя: </b></td>
                <td>@Html.EditorFor(m => m.Name) </td>
                <td> @Html.ValidationMessage("Name") </td>

            </tr>
            <tr>
                <td align="center" width="50%"><b>Фамилия: </b></td>
                <td>@Html.EditorFor(m => m.Sirname) </td>
                <td>@Html.ValidationMessage("Sirname") </td>

            </tr>
            <tr>
                <td align="center" width="50%"><b>Email: </b></td>
                <td>@Html.EditorFor(m => m.Email)</td>
                <td>@Html.ValidationMessage("Email") </td>

            </tr>
            <tr>
                <td align="center" width="50%"><b>Информация о вас: </b></td>
                <td>@Html.EditorFor(m => m.Info,new { height = "400px"}) </td>
                <td> @Html.ValidationMessage("Info") </td>

            </tr>
            <tr>
                <td align="center" width="50%" colspan="2"><br><input type="submit" value="Сохранить изменения" /></td>
            </tr>
        </table>
    </td>

        }

        @using (Html.BeginForm("EditPassword", "UserData", FormMethod.Post))
        {

            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.Login)
            @Html.HiddenFor(m => m.Name)
            @Html.HiddenFor(m => m.Sirname)
            @Html.HiddenFor(m => m.Email)
            @Html.HiddenFor(m => m.Info)

        <td width="10%"></td>
        <td width="30%">
            <table border="0" width="100%" align="center">
                <tr>

                    <h2><font color="green"><center> Изменение пароля </center></font></h2>
                    <br>
                    <br>

                    <td align="center" width="50%"><b>Введите старый пароль: </b></td>
                    <td>@Html.Password("oldPassword")</td>
                    <td>@ViewBag.oldPasswordMessage</td>
                </tr>

                <tr>
                    <td align="center" width="50%"><b> Введите новый пароль: </b></td>
                    <td>@Html.PasswordFor(m => m.Password)</td>
                    <td>@Html.ValidationMessage("Password")</td>
                </tr>

                <tr>

                    <td align="center" width="50%"><b>Повторите новый пароль: </b></td>
                    <td>@Html.PasswordFor(m => m.PasswordClone)</td>
                    <td>@Html.ValidationMessage("PasswordClone")</td>
                </tr>
                <tr>
                    <td align="center" width="50%" colspan="2"><br><input type="submit" value="Сохранить изменения" /></td>
                </tr>

            </table>

        </td>
            <td width="10%"></td>


        }
</tr></table>

UI/Views/UserData/Index.cshtml
@model UI.Models.UserModel

@{
    ViewBag.Title = "Персональная страница";
}
<br>
<table>
    <tr>
        <td width="25%"></td>
        <td width="50%">
            <h2><font color="green"><center> Персональная страница</center></font></h2>
            <br><br>
            <table border="0" width="100%" align="center" cellpadding="20">
                <tr>
                    <td>Ваш логин</td>
                    <td>@Html.DisplayFor(m => m.Login)</td>
                </tr>
                <tr>
                    <td>Ваше имя</td>
                    <td>
                        @Html.DisplayFor(m => m.Name)
                    </td>
                </tr>
                <tr>
                    <td>Ваша фамилия</td>
                    <td>
                        @Html.DisplayFor(m => m.Sirname)
                    </td>
                </tr>
                <tr>
                    <td>Информация о вас</td>
                    <td>
                        @Html.DisplayFor(m => m.Info)
                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="/UserData/AllProducts/?login=@Model.Login">К предложениям пользователя</a>
                    </td>
                </tr>
                </table>

                <td width="20%">
                    <img src="/Content/Images/who.jpg" width="150" height="150" align="right">
                </td>
    </tr>
</table>

UI/Views/UserData/MyProducts.cshtml
@using System.Collections.Generic;
@using UI.Models;

@model IEnumerable<ProductModel>
    @{
        ViewBag.Title = "Мои предложения";
    }
    <h2>Мои предложения</h2>
    @if (Model.Count() == 0) 
    {
        <p>Вы не добавили еще ни одного предложения</p>
    }
    else 
    {     
        foreach (ProductModel b in Model)
            {
            <tr>
                <td><p><a href="/ProductData/Index/@b.Id">@b.Name</a></p></td>
                <td><p>@b.Category</p></td>
                <td><p>@b.Rating</p></td>
                <td><p>от @b.MinValue рублей</p></td>
                <td><p></p></td>
            </tr>
            }
    }           

UI/Views/UserData/Register.cshtml
@model UI.Models.UserModel

@{
    ViewBag.Title = "Регистрация";
}
@using (Html.BeginForm("Register", "UserData", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <br>
    <table>
<tr><td width="30%"></td>
        <td>
    <h2><font color="green"><center> Регистрация </center></font></h2>
    <br><br>
    <table border="0" width="100%" align="left">
        <tr>
            <td align="right" width="50%"><b>Введите логин: </b></td>
            <td>@Html.TextBox("Login")</td>
            <td><font color="red">@Html.ValidationMessage("Login")</font></td>
        </tr>
        <tr>
            <td align="right" width="50%"><b>Введите пароль: </b></td>
            <td>@Html.Password("Password")</td>
            <td><font color="red">@Html.ValidationMessage("Password")</font></td>
        </tr>
        <tr>
            <td align="right" width="50%"><b>Повтор пароля: </b></td>
            <td>@Html.Password("PasswordClone")</td>
            <td><font color="red">@Html.ValidationMessage("PasswordClone")</font></td>
        </tr>
        <tr>
            <td align="right" width="50%"><b>Введите фамилию: </b></td>
            <td>@Html.TextBox("Sirname")</td>
            <td><font color="red">@Html.ValidationMessage("Sirname")</font></td>
        </tr>
        <tr>
            <td align="right" width="50%"><b>Введите имя: </b></td>
            <td>@Html.TextBox("Name")</td>
            <td><font color="red">@Html.ValidationMessage("Name")</font></td>
        </tr>
        <tr>
            <td align="right" width="50%"><b>Введите адрес электронной почты: </b></td>
            <td>@Html.TextBox("Email")</td>
            <td><font color="red">@Html.ValidationMessage("Email")</font></td>
        </tr>
        <tr>
            <td align="right" width="50%"><b>Введите информацию о себе: </b></td>
            <td>@Html.TextArea("Info")</td>
            <td><font color="red">@Html.ValidationMessage("Info")</font></td>
        </tr>
        <input type=hidden value=1 name= type>
        <tr>
            <td align="right"></td>
            <td>
                <input type=submit value="Отправить">
        </tr>
    </table>
</td>
    <td width="20%">
        <img src="/Content/Images/blocnot.jpg" width="150" height="150" align="right">
    </td></tr></table>
}